### ISSUE TITLE
Media Detection Error

### ISSUE THREAD

**Issue by AnjingLmao** [GuaiYiHu/android_device_xiaomi_whyred#12]
The song arrangement is different and the Gallery on Instagram showing older pictures. 

To reproduce this issue, reboot device multiple times.
![photo_2019-04-06_11-15-00](https://user-images.githubusercontent.com/49329681/55664209-66b74380-585d-11e9-8f4d-a56e6f2306ad.jpg)
![photo_2019-04-06_11-15-02](https://user-images.githubusercontent.com/49329681/55664210-674fda00-585d-11e9-8724-697b0a2dbb0c.jpg)
![photo_2019-04-06_11-15-05](https://user-images.githubusercontent.com/49329681/55664211-674fda00-585d-11e9-9c48-6f9ee3bbfecd.jpg)

After rebooting, take a look at this, the song arrangement will change.
![Inkedphoto_2019-04-06_11-17-15_LI](https://user-images.githubusercontent.com/49329681/55664237-d3cad900-585d-11e9-9e06-672520369e4d.jpg)
![photo_2019-04-06_11-17-09](https://user-images.githubusercontent.com/49329681/55664238-d3cad900-585d-11e9-8d2d-20e5f46b7185.jpg)
![photo_2019-04-06_11-17-11](https://user-images.githubusercontent.com/49329681/55664240-d3cad900-585d-11e9-8e3b-d97ed1e8d94e.jpg)
![photo_2019-04-06_11-17-19](https://user-images.githubusercontent.com/49329681/55664241-d4636f80-585d-11e9-9b13-48c440bf2330.jpg)

And you Guai Yi Hu. If you have balls, try unban me in your f*ckin Telegram @SaktisWRXSTi.
You are a f*cking arrogant dev. And f*ck your MoKee ROM you piece of shit. 肏你妈

**Comment by AnjingLmao** [comment]
Fucking communist.

**Comment by xingrz** [comment]
哈哈哈哈哈哈哈

**Comment by AnjingLmao** [comment]
厉害

**Comment by AnjingLmao** [comment]
厉害 da fei ji. @GuaiYiHu
