### ISSUE TITLE
OOS-MKDIR

### ISSUE THREAD

**Issue by SuaiYiHu** [GuaiYiHu/android_device_xiaomi_whyred#19]
sup cunt

miss me faggot?

idiot & arrogant chinese dev

**Comment by adi8900** [comment]
What the fuck is wrong with you?
Guaiyihu is one of best developers which i saw in live

**Comment by xingrz** [comment]
Go ahead, monkey. It's funny.

**Comment by TingyiChen** [comment]
lol happy urself:v
