### ISSUE TITLE
Note to upgrade blobs to pie.

### ISSUE THREAD

**Issue by GuaiYiHu** [GuaiYiHu/android_device_xiaomi_whyred#3]
Close till the work will be done...

**Comment by GuaiYiHu** [comment]
### persist
 guaiyihu@archlinux  ~/桌面/调教屋/A2/miui10  grep -r -i mnt/vendor/persist
Binary file system/lib/libsensor1.so matches
Binary file system/lib64/libsensor1.so matches
system/etc/mmi/path_config.xml:    <string name="mmi_ftm_ap_dir">/mnt/vendor/persist/FTM_AP/</string>
Binary file vendor/bin/tftp_server matches
Binary file vendor/bin/smart-pa-cal matches
Binary file vendor/bin/sensors.qti matches
Binary file vendor/bin/hvdcp_opti matches
Binary file vendor/bin/xtwifi-client matches
Binary file vendor/lib/libdrmfs.so matches
Binary file vendor/lib/hw/audio.primary.sdm660.so matches
Binary file vendor/lib/libsensor1.so matches
Binary file vendor/lib/libsdm-color.so matches
Binary file vendor/lib64/libdrmfs.so matches
Binary file vendor/lib64/hw/audio.primary.sdm660.so matches
Binary file vendor/lib64/libsensor1.so matches
Binary file vendor/lib64/libsdm-color.so matches
vendor/etc/init/hw/init.target.rc:    chown root system /mnt/vendor/persist
vendor/etc/init/hw/init.target.rc:    chmod 0771 /mnt/vendor/persist
vendor/etc/init/hw/init.target.rc:    mkdir /mnt/vendor/persist/data 0700 system system
vendor/etc/init/hw/init.target.rc:    mkdir /mnt/vendor/persist/bms 0700 root system
vendor/etc/init/hw/init.target.rc:    restorecon_recursive /mnt/vendor/persist
vendor/etc/init/hw/init.target.rc:    chown system system /mnt/vendor/persist/sensors/sns.reg
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/sns.reg
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/registry
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/registry/registry
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/registry/registry/sensors_registry
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/sensors_settings
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/registry/sns_reg_config
vendor/etc/init/hw/init.qcom.rc:    chown system system /mnt/vendor/persist/sensors/registry/config
vendor/etc/init/hw/init.qcom.rc:    chmod 0664 /mnt/vendor/persist/sensors/sensors_settings
vendor/etc/init/hw/init.qcom.rc:    mkdir /mnt/vendor/persist/secnvm 0770 system system
vendor/etc/init/hw/init.qcom.rc:    mkdir /mnt/vendor/persist/vpp 0770 media media
vendor/etc/init/hw/init.qcom.rc:    mkdir /mnt/vendor/persist/hvdcp_opti 0770 root system
vendor/etc/init/hw/init.qcom.rc:    mkdir /mnt/vendor/persist/audio 0770 root root
vendor/etc/init/hw/init.qcom.factory.rc:    mkdir /mnt/vendor/persist/FTM_AP 0750 system system
vendor/etc/init/hw/init.qcom.factory.rc:    mkdir /mnt/vendor/persist/FTM_AP 0750 system system
vendor/etc/fstab.qcom:/dev/block/bootdevice/by-name/persist    /mnt/vendor/persist   ext4   noatime,nosuid,nodev,barrier=1                   wait

**Comment by TingyiChen** [comment]
🔨调教屋

**Comment by SubDragonzj** [comment]
hammer调教屋

**Comment by GuaiYiHu** [comment]
# Done

# Alarm - from 
framework/vendor.qti.hardware.alarm-V1.0-java.jar
-vendor/app/PowerOffAlarm/PowerOffAlarm.apk
vendor/bin/hw/vendor.qti.hardware.alarm@1.0-service
vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc
vendor/lib64/hw/vendor.qti.hardware.alarm@1.0-impl.so
vendor/lib64/vendor.qti.hardware.alarm@1.0.so

# Bluetooth - from 
vendor/bin/btnvtool
vendor/bin/hci_qcomm_init
vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti
vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc
vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so
vendor/lib/libbt-hidlclient.so
vendor/lib/libbtnv.so
vendor/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so
vendor/lib64/libbt-hidlclient.so
vendor/lib64/libbtnv.so

# Charger - from 
vendor/bin/hvdcp_opti|9d0efda6f5cc8a03295690368ae823117a453d35

# CNE - from 
etc/permissions/cneapiclient.xml
etc/permissions/com.quicinc.cne.xml
framework/cneapiclient.jar
framework/com.quicinc.cne.api-V1.0-java.jar
framework/com.quicinc.cne.api-V1.1-java.jar
framework/com.quicinc.cne.constants-V1.0-java.jar
framework/com.quicinc.cne.constants-V2.0-java.jar
framework/com.quicinc.cne.constants-V2.1-java.jar
framework/com.quicinc.cne.jar
framework/com.quicinc.cne.server-V1.0-java.jar
framework/com.quicinc.cne.server-V2.0-java.jar
framework/com.quicinc.cne.server-V2.1-java.jar
framework/com.quicinc.cne.server-V2.2-java.jar
framework/vendor.qti.data.factory-V1.0-java.jar
framework/vendor.qti.hardware.data.qmi-V1.0-java.jar
-priv-app/CNEService/CNEService.apk
vendor/bin/cnd
vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml
vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml
vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml
vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml
vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml
vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml
vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml
vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml
-vendor/lib64/com.quicinc.cne.api@1.0.so
-vendor/lib64/com.quicinc.cne.api@1.1.so
-vendor/lib64/com.quicinc.cne.constants@1.0.so
-vendor/lib64/com.quicinc.cne.constants@2.0.so
-vendor/lib64/com.quicinc.cne.constants@2.1.so
-vendor/lib64/com.quicinc.cne.server@2.0.so
-vendor/lib64/com.quicinc.cne.server@2.1.so
-vendor/lib64/com.quicinc.cne.server@2.2.so
vendor/lib64/libcne.so
vendor/lib64/libcneapiclient.so
vendor/lib64/libcneoplookup.so
vendor/lib64/libcneqmiutils.so
vendor/lib64/libwms.so
vendor/lib64/libwqe.so
vendor/lib64/libxml.so
vendor/lib64/vendor.qti.hardware.data.latency@1.0.so
vendor/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so
vendor/lib64/vendor.qti.hardware.data.qmi@1.0.so
vendor/lib64/vendor.qti.data.factory@1.0.so
vendor/lib64/vendor.qti.ims.rcsconfig@1.0.so
vendor/lib64/vendor.qti.latency@2.0.so

# DPM - from 
bin/dpmd
etc/dpm/dpm.conf
etc/init/dpmd.rc
etc/permissions/com.qti.dpmframework.xml
etc/permissions/dpmapi.xml
framework/com.qti.dpmframework.jar
framework/dpmapi.jar
framework/tcmclient.jar
-priv-app/dpmserviceapp/dpmserviceapp.apk
lib64/com.qualcomm.qti.dpm.api@1.0.so
lib64/libdpmctmgr.so
lib64/libdpmfdmgr.so
lib64/libdpmframework.so
lib64/libdpmtcm.so
vendor/bin/dpmQmiMgr
vendor/lib64/libdpmqmihal.so
vendor/lib64/com.qualcomm.qti.dpm.api@1.0.so

# DRM - Widevine - from 
vendor/bin/hw/android.hardware.drm@1.1-service.widevine
vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc
vendor/lib/mediadrm/libwvdrmengine.so
vendor/lib64/libwvhidl.so
vendor/lib64/mediadrm/libwvdrmengine.so

# ESE-Powermanager - from 
vendor/bin/hw/vendor.qti.esepowermanager@1.0-service
vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc
lib/vendor.qti.esepowermanager@1.0.so
lib64/vendor.qti.esepowermanager@1.0.so
vendor/lib/hw/vendor.qti.esepowermanager@1.0-impl.so
vendor/lib64/hw/vendor.qti.esepowermanager@1.0-impl.so

# FM - from 
lib/libfm-hci.so
lib/fm_helium.so
lib64/libfm-hci.so
lib64/fm_helium.so
vendor/bin/fm_qsoc_patches
-lib/vendor.qti.hardware.fm@1.0.so
-lib64/vendor.qti.hardware.fm@1.0.so
vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so
vendor/lib/vendor.qti.hardware.fm@1.0.so
vendor/lib64/hw/vendor.qti.hardware.fm@1.0-impl.so
vendor/lib64/vendor.qti.hardware.fm@1.0.so

# GPS - from 
vendor/bin/hw/vendor.qti.gnss@2.0-service
vendor/bin/DR_AP_Service
vendor/bin/garden_app
vendor/bin/loc_launcher
vendor/bin/lowi-server
vendor/bin/slim_daemon
vendor/bin/xtra-daemon
vendor/etc/cacert_location.pem
vendor/etc/xtra_root_cert.pem
vendor/etc/init/vendor.qti.gnss@2.0-service.rc
vendor/lib64/hw/vendor.qti.gnss@2.0-impl.so
vendor/lib64/lib_drplugin_server.so
vendor/lib64/libalarmservice_jni.so
vendor/lib64/libdataitems.so
vendor/lib64/libdrplugin_client.so
vendor/lib64/libDRPlugin.so
vendor/lib64/libevent_observer.so
vendor/lib64/libflp.so
vendor/lib64/libgdtap.so
vendor/lib64/libgeofence.so
vendor/lib64/libizat_client_api.so
vendor/lib64/libizat_core.so
vendor/lib64/liblbs_core.so
vendor/lib64/libloc_api_v02.so
vendor/lib64/libloc_ds_api.so
vendor/lib64/libloc_externalDr.so
vendor/lib64/liblocationservice_glue.so
vendor/lib64/liblocationservice.so
vendor/lib64/liblowi_client.so
vendor/lib64/liblowi_wifihal.so
vendor/lib64/libquipc_os_api.so
vendor/lib64/libslimclient.so
vendor/lib64/libulp2.so
vendor/lib64/libxtadapter.so
vendor/lib64/libxtwifi_ulp_adaptor.so
vendor/lib64/vendor.qti.gnss@1.0.so
vendor/lib64/vendor.qti.gnss@1.1.so
vendor/lib64/vendor.qti.gnss@1.2.so
vendor/lib64/vendor.qti.gnss@2.0.so

# Graphics - from 
vendor/lib64/egl/eglSubDriverAndroid.so
vendor/lib64/egl/libEGL_adreno.so
vendor/lib64/egl/libGLESv1_CM_adreno.so
vendor/lib64/egl/libGLESv2_adreno.so
vendor/lib64/egl/libq3dtools_adreno.so
vendor/lib64/egl/libq3dtools_esx.so
vendor/lib64/egl/libQTapGLES.so
vendor/lib64/libadreno_utils.so
vendor/lib64/libbccQTI.so
vendor/lib64/libC2D2.so
vendor/lib64/libc2d30_bltlib.so
vendor/lib64/libCB.so
vendor/lib64/libgsl.so
vendor/lib64/libllvm-glnext.so
vendor/lib64/libllvm-qcom.so
vendor/lib64/libllvm-qgl.so
vendor/lib64/libmm-disp-apis.so
vendor/lib64/libmm-qdcm.so
vendor/lib64/libOpenCL.so
vendor/lib64/librs_adreno_sha1.so
vendor/lib64/librs_adreno.so
vendor/lib64/libRSDriver_adreno.so
vendor/lib/egl/eglSubDriverAndroid.so
vendor/lib/egl/libEGL_adreno.so
vendor/lib/egl/libGLESv1_CM_adreno.so
vendor/lib/egl/libGLESv2_adreno.so
vendor/lib/egl/libq3dtools_adreno.so
vendor/lib/egl/libq3dtools_esx.so
vendor/lib/egl/libQTapGLES.so
vendor/lib/libadreno_utils.so
vendor/lib/libbccQTI.so
vendor/lib/libC2D2.so
vendor/lib/libc2d30_bltlib.so
vendor/lib/libCB.so
vendor/lib/libgsl.so
vendor/lib/libllvm-glnext.so
vendor/lib/libllvm-qcom.so
vendor/lib/libOpenCL.so
vendor/lib/librs_adreno_sha1.so
vendor/lib/librs_adreno.so
vendor/lib/libRSDriver_adreno.so

# Graphics (HDR) - from 
vendor/lib/libhdr_tm.so
vendor/lib64/libhdr_tm.so

# Graphics (SDM) - from 
vendor/lib/libqseed3.so
vendor/lib/libsdm-color.so
vendor/lib/libsdm-diag.so
-vendor/lib/libsdm-disp-vndapis.so
vendor/lib/libsdmextension.so
vendor/lib/libtinyxml2_1.so
vendor/lib64/libqseed3.so
vendor/lib64/libsdm-color.so
vendor/lib64/libsdm-diag.so
-vendor/lib64/libsdm-disp-vndapis.so
vendor/lib64/libsdmextension.so
vendor/lib64/libtinyxml2_1.so

# Graphics (Vulkan) - from 
vendor/lib/hw/vulkan.sdm660.so
vendor/lib64/hw/vulkan.sdm660.so

# Listen - from 
vendor/lib/hw/sound_trigger.primary.sdm660.so
vendor/lib/libadpcmdec.so
vendor/lib/libgcs-calwrapper.so
vendor/lib/libgcs-ipc.so
vendor/lib/libgcs-osal.so
vendor/lib/libgcs.so
vendor/lib/libsmwrapper.so
vendor/lib64/hw/sound_trigger.primary.sdm660.so
vendor/lib64/libgcs-calwrapper.so
vendor/lib64/libgcs-ipc.so
vendor/lib64/libgcs-osal.so
vendor/lib64/libgcs.so

# Media - from 
lib/libmmosal.so
lib/vendor.qti.hardware.vpp@1.1.so
lib64/libmmosal.so
lib64/vendor.qti.hardware.vpp@1.1.so
vendor/lib/libAlacSwDec.so
vendor/lib/libApeSwDec.so
vendor/lib/libdsd2pcm.so
vendor/lib/libFlacSwDec.so
-vendor/lib/libgpustats.so
vendor/lib/libvpplibrary.so
vendor/lib/libI420colorconvert.so
vendor/lib/libmm-color-convertor.so
vendor/lib/libmmosal_proprietary.so
vendor/lib/libmmsw_detail_enhancement.so
vendor/lib/libmmsw_math.so
vendor/lib/libmmsw_opencl.so
vendor/lib/libmmsw_platform.so
vendor/lib/libOmxAacDec.so
vendor/lib/libOmxEvrcDec.so
vendor/lib/libOmxQcelp13Dec.so
vendor/lib/libOmxVpp.so
vendor/lib/libOmxAlacDec.so
vendor/lib/libOmxAlacDecSw.so
vendor/lib/libOmxAmrDec.so
vendor/lib/libOmxAmrwbplusDec.so
vendor/lib/libOmxApeDec.so
vendor/lib/libOmxApeDecSw.so
vendor/lib/libOmxDsdDec.so
vendor/lib/libOmxG711Dec.so
vendor/lib/libOmxVideoDSMode.so
vendor/lib/libOmxWmaDec.so
vendor/lib/libvpphvx.so
vendor/lib/libvqzip.so
vendor/lib/libvpptestutils.so
vendor/lib/vendor.qti.hardware.vpp@1.1.so
vendor/lib64/libAlacSwDec.so
vendor/lib64/libApeSwDec.so
vendor/lib64/libFlacSwDec.so
-vendor/lib64/libgpustats.so
vendor/lib64/libI420colorconvert.so
vendor/lib64/libmm-color-convertor.so
vendor/lib64/libmmosal_proprietary.so
vendor/lib64/libmmsw_detail_enhancement.so
vendor/lib64/libmmsw_math.so
vendor/lib64/libmmsw_opencl.so
vendor/lib64/libmmsw_platform.so
vendor/lib64/libOmxAacDec.so
vendor/lib64/libOmxAlacDec.so
vendor/lib64/libOmxAlacDecSw.so
vendor/lib64/libOmxAmrDec.so
vendor/lib64/libOmxAmrwbplusDec.so
vendor/lib64/libOmxApeDec.so
vendor/lib64/libOmxApeDecSw.so
vendor/lib64/libOmxEvrcDec.so
vendor/lib64/libOmxG711Dec.so
vendor/lib64/libOmxQcelp13Dec.so
vendor/lib64/libOmxVpp.so
vendor/lib64/libOmxWmaDec.so
vendor/lib64/libvpplibrary.so
vendor/lib64/libvpphvx.so
vendor/lib64/libvpptestutils.so
vendor/lib64/vendor.qti.hardware.vpp@1.1.so

# Peripheral manager - from 
vendor/bin/pm-proxy
vendor/bin/pm-service
vendor/lib/libperipheral_client.so
vendor/lib64/libperipheral_client.so

# Postprocessing - from 
vendor/bin/hw/vendor.display.color@1.0-service
vendor/bin/mm-pp-dpps
vendor/etc/init/vendor.display.color@1.0-service.rc
vendor/lib64/libdisp-aba.so
vendor/lib64/vendor.display.color@1.0.so
vendor/lib64/vendor.display.color@1.1.so
vendor/lib64/vendor.display.postproc@1.0.so

# Time services - from 
-vendor/app/TimeService/TimeService.apk
vendor/bin/time_daemon
vendor/lib64/libtime_genoff.so

# Wifi - from 
vendor/bin/cnss-daemon

**Comment by GuaiYiHu** [comment]
# QMI - 
lib64/libqminvapi.so:vendor/lib64/libqminvapi.so
etc/permissions/qti_libpermissions.xml
etc/permissions/qti_permissions.xml
lib/libdiag_system.so
lib64/libdiag_system.so
vendor/bin/irsc_util
vendor/lib/libdiag.so
vendor/lib/libdsutils.so
vendor/lib/libidl.so
vendor/lib/libqcci_legacy.so
vendor/lib/libqdi.so
vendor/lib/libqdp.so
vendor/lib/libqmi_cci.so
vendor/lib/libqmi_client_helper.so
vendor/lib/libqmi_client_qmux.so
vendor/lib/libqmi_common_so.so
vendor/lib/libqmi_csi.so
vendor/lib/libqmi_encdec.so
vendor/lib/libqmi.so
vendor/lib/libqmiservices.so
vendor/lib64/libdiag.so
vendor/lib64/libdsutils.so
vendor/lib64/libidl.so
vendor/lib64/libqcci_legacy.so
vendor/lib64/libqdi.so
vendor/lib64/libqdp.so
vendor/lib64/libqmi_cci.so
vendor/lib64/libqmi_client_helper.so
vendor/lib64/libqmi_client_qmux.so
vendor/lib64/libqmi_common_so.so
vendor/lib64/libqmi_csi.so
vendor/lib64/libqmi_encdec.so
vendor/lib64/libqmi.so
vendor/lib64/libqminvapi.so
vendor/lib64/libqmiservices.so

# RIL - 
-app/datastatusnotification/datastatusnotification.apk
-app/QtiTelephonyService/QtiTelephonyService.apk
etc/permissions/lpa.xml
etc/permissions/qcrilhook.xml
etc/permissions/telephonyservice.xml
framework/qcrilhook.jar
framework/qti-telephony-common.jar
framework/QtiTelephonyServicelibrary.jar
framework/uimlpalibrary.jar
-priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk
vendor/bin/ATFWD-daemon
vendor/bin/ipacm-diag
vendor/bin/netmgrd
vendor/bin/pd-mapper
vendor/bin/qti
vendor/bin/rmt_storage
vendor/bin/tftp_server
vendor/etc/data/dsi_config.xml
vendor/etc/data/netmgr_config.xml
vendor/lib/libmdmdetect.so
vendor/lib64/libconfigdb.so
vendor/lib64/libdsi_netctrl.so
vendor/lib64/liblqe.so
vendor/lib64/libmdmdetect.so
vendor/lib64/libnetmgr.so
vendor/lib64/libnlnetmgr.so
vendor/lib64/libnetmgr_common.so
vendor/lib64/libnetmgr_nr_fusion.so
vendor/lib64/libnetmgr_rmnet_ext.so
vendor/lib64/libpdmapper.so
vendor/lib64/libpdnotifier.so
vendor/lib64/libqcmaputils.so
vendor/lib64/libqrtr.so
vendor/lib64/libqsocket.so
vendor/lib64/libqcrilFramework.so
vendor/lib64/libril-qc-hal-qmi.so
vendor/lib64/libril-qc-ltedirectdisc.so
vendor/lib64/libril-qc-qmi-1.so
vendor/lib64/libril-qc-radioconfig.so
vendor/lib64/libril-qcril-hook-oem.so
vendor/lib64/librilqmiservices.so
vendor/lib64/libsettings.so
vendor/lib64/libsystem_health_mon.so
vendor/lib64/vendor.qti.hardware.radio.am@1.0.so
vendor/lib64/vendor.qti.hardware.radio.atcmdfwd@1.0.so
vendor/lib64/vendor.qti.hardware.radio.lpa@1.0.so
vendor/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so
vendor/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so
vendor/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so
vendor/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so
vendor/lib64/vendor.qti.hardware.radio.uim@1.0.so
vendor/lib64/vendor.qti.hardware.radio.uim@1.1.so
vendor/radio/qcril_database/qcril.db

# IMS - 
-priv-app/ims/ims.apk
framework/com.qualcomm.qti.imscmservice-V2.0-java.jar
framework/vendor.qti.ims.rcsconfig-V1.0-java.jar
lib64/com.qualcomm.qti.imscmservice@2.0.so
lib64/com.qualcomm.qti.imscmservice@2.1.so
lib64/com.qualcomm.qti.uceservice@2.0.so
lib64/lib-imscamera.so
lib64/lib-imsvideocodec.so
lib64/lib-imsvt.so
lib64/lib-imsvtextutils.so
lib64/lib-imsvtutils.so
lib64/libimscamera_jni.so
lib64/libimsmedia_jni.so
lib64/librcc.so
lib64/vendor.qti.imsrtpservice@1.0.so
vendor/bin/ims_rtp_daemon
vendor/bin/imsdatadaemon
vendor/bin/imsqmidaemon
vendor/bin/imsrcsd
vendor/lib64/lib-dplmedia.so
vendor/lib64/lib-imscmservice.so
vendor/lib64/lib-imsdpl.so
vendor/lib64/lib-imsrcsbaseimpl.so
vendor/lib64/lib-imsqimf.so
vendor/lib64/lib-imsrcs-v2.so
vendor/lib64/lib-imsxml.so
vendor/lib64/lib-rtpcommon.so
vendor/lib64/lib-rtpcore.so
vendor/lib64/lib-rtpdaemoninterface.so
vendor/lib64/lib-rtpsl.so
vendor/lib64/lib-siputility.so
vendor/lib64/lib-uceservice.so
vendor/lib64/vendor.qti.hardware.radio.ims@1.0.so
vendor/lib64/vendor.qti.hardware.radio.ims@1.1.so
vendor/lib64/vendor.qti.hardware.radio.ims@1.2.so
vendor/lib64/vendor.qti.hardware.radio.ims@1.3.so
vendor/lib64/vendor.qti.hardware.radio.ims@1.4.so
vendor/lib64/vendor.qti.ims.callinfo@1.0.so
vendor/lib64/vendor.qti.ims.rcsconfig@1.0.so
vendor/lib64/vendor.qti.imsrtpservice@1.0.so
vendor/lib64/vendor.qti.imsrtpservice@1.0-service-Impl.so

vendor/lib64/vendor.qti.hardware.radio.qtiradio@2.0.so
lib64/android.hardware.radio.config@1.0.so
lib64/android.hardware.secure_element@1.0.so
vendor/lib64/qcrild_librilutils.so
lib64/android.hardware.radio@1.2.so

**Comment by GuaiYiHu** [comment]
> # TODO
> ===========
> 
> # QMI -
> lib64/libqminvapi.so:vendor/lib64/libqminvapi.so
> etc/permissions/qti_libpermissions.xml
> etc/permissions/qti_permissions.xml
> lib/libdiag_system.so
> lib64/libdiag_system.so
> vendor/bin/irsc_util
> vendor/lib/libdiag.so
> vendor/lib/libdsutils.so
> vendor/lib/libidl.so
> vendor/lib/libqcci_legacy.so
> vendor/lib/libqdi.so
> vendor/lib/libqdp.so
> vendor/lib/libqmi_cci.so
> vendor/lib/libqmi_client_helper.so
> vendor/lib/libqmi_client_qmux.so
> vendor/lib/libqmi_common_so.so
> vendor/lib/libqmi_csi.so
> vendor/lib/libqmi_encdec.so
> vendor/lib/libqmi.so
> vendor/lib/libqmiservices.so
> vendor/lib64/libdiag.so
> vendor/lib64/libdsutils.so
> vendor/lib64/libidl.so
> vendor/lib64/libqcci_legacy.so
> vendor/lib64/libqdi.so
> vendor/lib64/libqdp.so
> vendor/lib64/libqmi_cci.so
> vendor/lib64/libqmi_client_helper.so
> vendor/lib64/libqmi_client_qmux.so
> vendor/lib64/libqmi_common_so.so
> vendor/lib64/libqmi_csi.so
> vendor/lib64/libqmi_encdec.so
> vendor/lib64/libqmi.so
> vendor/lib64/libqminvapi.so
> vendor/lib64/libqmiservices.so
> 
> # RIL -
> -app/datastatusnotification/datastatusnotification.apk
> -app/QtiTelephonyService/QtiTelephonyService.apk
> etc/permissions/lpa.xml
> etc/permissions/qcrilhook.xml
> etc/permissions/telephonyservice.xml
> framework/qcrilhook.jar
> framework/qti-telephony-common.jar
> framework/QtiTelephonyServicelibrary.jar
> framework/uimlpalibrary.jar
> -priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk
> vendor/bin/ATFWD-daemon
> vendor/bin/ipacm-diag
> vendor/bin/netmgrd
> vendor/bin/pd-mapper
> vendor/bin/qti
> vendor/bin/rmt_storage
> vendor/bin/tftp_server
> vendor/etc/data/dsi_config.xml
> vendor/etc/data/netmgr_config.xml
> vendor/lib/libmdmdetect.so
> vendor/lib64/libconfigdb.so
> vendor/lib64/libdsi_netctrl.so
> vendor/lib64/liblqe.so
> vendor/lib64/libmdmdetect.so
> vendor/lib64/libnetmgr.so
> vendor/lib64/libnlnetmgr.so
> vendor/lib64/libnetmgr_common.so
> vendor/lib64/libnetmgr_nr_fusion.so
> vendor/lib64/libnetmgr_rmnet_ext.so
> vendor/lib64/libpdmapper.so
> vendor/lib64/libpdnotifier.so
> vendor/lib64/libqcmaputils.so
> vendor/lib64/libqrtr.so
> vendor/lib64/libqsocket.so
> vendor/lib64/libqcrilFramework.so
> vendor/lib64/libril-qc-hal-qmi.so
> vendor/lib64/libril-qc-ltedirectdisc.so
> vendor/lib64/libril-qc-qmi-1.so
> vendor/lib64/libril-qc-radioconfig.so
> vendor/lib64/libril-qcril-hook-oem.so
> vendor/lib64/librilqmiservices.so
> vendor/lib64/libsettings.so
> vendor/lib64/libsystem_health_mon.so
> vendor/lib64/vendor.qti.hardware.radio.am@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.atcmdfwd@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.lpa@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.uim@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.uim@1.1.so
> vendor/radio/qcril_database/qcril.db
> 
> # IMS -
> -priv-app/ims/ims.apk
> framework/com.qualcomm.qti.imscmservice-V2.0-java.jar
> framework/vendor.qti.ims.rcsconfig-V1.0-java.jar
> lib64/com.qualcomm.qti.imscmservice@2.0.so
> lib64/com.qualcomm.qti.imscmservice@2.1.so
> lib64/com.qualcomm.qti.uceservice@2.0.so
> lib64/lib-imscamera.so
> lib64/lib-imsvideocodec.so
> lib64/lib-imsvt.so
> lib64/lib-imsvtextutils.so
> lib64/lib-imsvtutils.so
> lib64/libimscamera_jni.so
> lib64/libimsmedia_jni.so
> lib64/librcc.so
> lib64/vendor.qti.imsrtpservice@1.0.so
> vendor/bin/ims_rtp_daemon
> vendor/bin/imsdatadaemon
> vendor/bin/imsqmidaemon
> vendor/bin/imsrcsd
> vendor/lib64/lib-dplmedia.so
> vendor/lib64/lib-imscmservice.so
> vendor/lib64/lib-imsdpl.so
> vendor/lib64/lib-imsrcsbaseimpl.so
> vendor/lib64/lib-imsqimf.so
> vendor/lib64/lib-imsrcs-v2.so
> vendor/lib64/lib-imsxml.so
> vendor/lib64/lib-rtpcommon.so
> vendor/lib64/lib-rtpcore.so
> vendor/lib64/lib-rtpdaemoninterface.so
> vendor/lib64/lib-rtpsl.so
> vendor/lib64/lib-siputility.so
> vendor/lib64/lib-uceservice.so
> vendor/lib64/vendor.qti.hardware.radio.ims@1.0.so
> vendor/lib64/vendor.qti.hardware.radio.ims@1.1.so
> vendor/lib64/vendor.qti.hardware.radio.ims@1.2.so
> vendor/lib64/vendor.qti.hardware.radio.ims@1.3.so
> vendor/lib64/vendor.qti.hardware.radio.ims@1.4.so
> vendor/lib64/vendor.qti.ims.callinfo@1.0.so
> vendor/lib64/vendor.qti.ims.rcsconfig@1.0.so
> vendor/lib64/vendor.qti.imsrtpservice@1.0.so
> vendor/lib64/vendor.qti.imsrtpservice@1.0-service-Impl.so
> 
> vendor/lib64/vendor.qti.hardware.radio.qtiradio@2.0.so
> lib64/android.hardware.radio.config@1.0.so
> lib64/android.hardware.secure_element@1.0.so
> vendor/lib64/qcrild_librilutils.so
> lib64/android.hardware.radio@1.2.so

**Comment by twistloop** [comment]
Testing the radio blobs from Mi A2.

**Comment by twistloop** [comment]
After picking the commits' from tree and vendor, the device passes splash and is stuck at boot animation. I can provide logs if required.

**Comment by GuaiYiHu** [comment]
# Left
audio
perf
thermal
