### ISSUE TITLE
lets talk

### ISSUE THREAD

**Issue by SuaiYIPooh** [GuaiYiHu/android_device_xiaomi_whyred#31]
@xingrz 

I did not build MoKee. The thing is, this Guai Yi Hu (not so 乖) told me if MoKee has this media detection issues. 

well, i followed his orders and guess what, the problem still persists. I reported to him and guess what he said: 

DONOT disturb if you are not using MoKee
DONOT disture if you are not using my kernel.

I mean like wtf is this dude replying. If you don't like to help. just say so. don't be so 笨蛋. At least use 你的脑.

**Comment by xingrz** [comment]
You're using somebody else's fork. You're not using MoKee. The MoKee developer doesn't have the responsibility to tell you anything about somebody else's fork.
