### ISSUE TITLE
Stuck on "Wrong base firmware"

### ISSUE THREAD

**Issue by kswro** [GuaiYiHu/android_device_xiaomi_whyred#35]
Hello, I'm stuck on "FBI WARNING - WRONG BASE FIRMWARE" on several nightly release (latest attempt on 20190408, downloaded from Mokee Center apps). Please help.

TWRP: 3.2.3-2 official

Firmware: 9.3.25

Device: Whyred RN5Pro Global

**Comment by xingrz** [comment]
Upgrade to the *right* firmware.

**Comment by kswro** [comment]
So, which version is the "right" firmware? I believe I installed the latest firmware for whyred (I also installed beta 9.3.28 PIE but still stuck). Thanks for your help.

**Comment by GuaiYiHu** [comment]
https://www.androidfilehost.com/?fid=1395089523397934058
