### ISSUE TITLE
DT2W broken on some touchpanels

### ISSUE THREAD

**Issue by aarow9** [GuaiYiHu/android_device_xiaomi_whyred#36]
On latest nightly build as well as previous mokee builds...d2tw isn't working on my device. I have a tianma td4310 touchpanel fyi. Can you please look into it. Thanks.

**Comment by GuaiYiHu** [comment]
Tested on my own tianma td4310 screen, dt2w does works.

**Comment by aarow9** [comment]
Oh. Do I need to be on latest firmware? I still have no idea why it ain't working on my device. Anyway, thanks for replying I will try to clean flash and check.

**Comment by aarow9** [comment]
Updated to latest firwmare but still d2tw doesn't work. My log shows this

[  112.365000] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.365146] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 9
[  112.415277] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.415426] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 10
[  112.436988] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C read over retry limit
[  112.437057] synaptics_dsx_i2c 1-0020: synaptics_rmi4_sensor_report: Failed to read interrupt status
[  112.438127] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x20 MSTR_STS:0x001321c4 OPER:0x00000010
[  112.438229] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 1
[  112.490758] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.490853] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 2
[  112.543331] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.543569] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 3
[  112.595365] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.595478] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 4
[  112.641737] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.641859] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 5
[  112.663581] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x20 MSTR_STS:0x001121c4 OPER:0x00000000
[  112.663663] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 6
[  112.686867] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x2c MSTR_STS:0x001121c4 OPER:0x00000000
[  112.686931] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 7
