### ISSUE TITLE
Updated to latest firwmare but still dt2w doesn't work. My log shows this

### ISSUE THREAD

**Issue by aarow9** [GuaiYiHu/android_device_xiaomi_whyred#37]
Updated to latest firwmare but still d2tw doesn't work. My log shows this

[    0.542600] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0x8 MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.542731] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0x8 MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.542848] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0x8 MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.542965] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0x8 MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.542989] I2C PMIC: i2c_pmic_read: i2c_pmic_read failed for 3 retries, rc = -107
[    0.542994] I2C PMIC: i2c_pmic_determine_initial_status: Couldn't read irq data rc=-107
[    0.543000] I2C PMIC: i2c_pmic_probe: Couldn't determine initial status rc=-107
[    0.543059] i2c_pmic: probe of 2-0008 failed with error -107
[    0.543375] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0xc MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.543493] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0xc MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.543609] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0xc MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.543724] i2c-msm-v2 c176000.i2c: NACK: slave not responding, ensure its powered: msgs(n:2 cur:0 tx) bc(rx:5 tx:2) mode:FIFO slv_addr:0xc MSTR_STS:0x0d1300c8 OPER:0x00000010
[    0.543747] I2C PMIC: i2c_pmic_read: i2c_pmic_read failed for 3 retries, rc = -107
[    0.543752] I2C PMIC: i2c_pmic_determine_initial_status: Couldn't read irq data rc=-107
[    0.543757] I2C PMIC: i2c_pmic_probe: Couldn't determine initial status rc=-107
[    0.543783] i2c_pmic: probe of 2-000c failed with error -107

[    0.613094] [NVT-ts] nvt_driver_init 1770: start
[    0.613127] [NVT-ts] nvt_ts_probe 1243: start
[    0.613200] [NVT-ts] nvt_parse_dt 885: novatek,irq-gpio=67
[    0.613230] [NVT-ts] nvt_parse_dt 887: novatek,reset-gpio=66
[    0.613236] [NVT-ts] nvt_gpio_config 911: Failed to request NVT-int GPIO
[    0.613241] [NVT-ts] nvt_ts_probe 1260: gpio config error!
[    0.613254] NVT-ts: probe of 1-0062 failed with error -16
[    0.613276] nvt_driver_init: finished

[  112.365000] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.365146] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 9
[  112.415277] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.415426] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 10
[  112.436988] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C read over retry limit
[  112.437057] synaptics_dsx_i2c 1-0020: synaptics_rmi4_sensor_report: Failed to read interrupt status
[  112.438127] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x20 MSTR_STS:0x001321c4 OPER:0x00000010
[  112.438229] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 1
[  112.490758] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.490853] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 2
[  112.543331] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.543569] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 3
[  112.595365] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.595478] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 4
[  112.641737] i2c-msm-v2 c175000.i2c: error timeout on polling for valid state. check core_clk
[  112.641859] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 5
[  112.663581] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x20 MSTR_STS:0x001121c4 OPER:0x00000000
[  112.663663] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 6
[  112.686867] i2c-msm-v2 c175000.i2c: BUS ERROR:noisy bus/unexpected start/stop tag: msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x2c MSTR_STS:0x001121c4 OPER:0x00000000
[  112.686931] synaptics_dsx_i2c 1-0020: synaptics_rmi4_i2c_read: I2C retry 7

Attaching full dmesg if it helps.
[dmes.txt](https://github.com/GuaiYiHu/android_device_xiaomi_whyred/files/3076410/dm.txt)

_Originally posted by @aarow9 in https://github.com/GuaiYiHu/android_device_xiaomi_whyred/issues/36#issuecomment-482809856_

**Comment by TheGlitchh** [comment]
well the provided link is not working anymore , can you  update the link ?
