### ISSUE TITLE
请教大佬，怎么从android源码开始编译自己的rom呢？

### ISSUE THREAD

**Issue by Remember2018** [GuaiYiHu/android_device_xiaomi_whyred#41]
大佬，我有一个红米note2的机器，但是官方的开发包是android 5.0的。现在我想研究如何从新版本的android编译这台机器的rom。我的想法是，应该是从官方那个小米开源代码里面，抽取跟设备相关的驱动代码到新版本的android里面就行了吧？但是怎么知道哪些代码是跟设备相关的呢？请问大佬这是一条明路吗？

**Comment by xingrz** [comment]
https://bbs.mokeedev.com/t/topic/1073/1

**Comment by Remember2018** [comment]
@xingrz 谢谢大佬的回复！
