### ISSUE TITLE
resouce not found 

### ISSUE THREAD

**Issue by buatge** [GuaiYiHu/android_device_xiaomi_whyred#5]
编译的时候报了资源找不到的问题。请问遇到过吗？
[  0% 53/28724] AAPT2 link /home/andro...aomiDoze_intermediates/package-res.apk
FAILED: /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/package-res.apk
/bin/bash -c "(rm -f /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-list ) && (touch /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-list ) && (rm -f /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-overlay-list ) && (touch /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-overlay-list ) && (echo -n '/home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v14-preference_intermediates/package-res.apk /home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-appcompat_intermediates/package-res.apk /home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-preference_intermediates/package-res.apk /home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-recyclerview_intermediates/package-res.apk /home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v13_intermediates/package-res.apk /home/androidSource/out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/package-res.apk /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/flat-res/device/xiaomi/whyred/doze/res/drawable_switchbar_background.xml.flat /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/flat-res/device/xiaomi/whyred/doze/res/layout_doze.xml.flat /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/flat-res/device/xiaomi/whyred/doze/res/layout_switch_bar.xml.flat /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/flat-res/device/xiaomi/whyred/doze/res/values_styles.arsc.flat /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/flat-res/device/xiaomi/whyred/doze/res/xml_doze_settings.xml.flat ' >> /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-overlay-list ) && (/home/androidSource/out/host/linux-x86/bin/aapt2 link -o /home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/package-res.apk -z --no-static-lib-packages --auto-add-overlay --manifest device/xiaomi/whyred/doze/AndroidManifest.xml -I /home/androidSource/out/target/common/obj/APPS/framework-res_intermediates/package-export.apk -I /home/androidSource/out/target/common/obj/APPS/org.mokee.platform-res_intermediates/package-export.apk   --java /home/androidSource/out/target/common/obj/APPS/XiaomiDoze_intermediates/src --proguard /home/androidSource/out/target/common/obj/APPS/XiaomiDoze_intermediates/proguard_options --min-sdk-version 27 --target-sdk-version 27 --product default -c zh_CN,en_US,cs_CZ,da_DK,de_AT,de_CH,de_DE,de_LI,el_GR,en_AU,en_CA,en_GB,en_NZ,en_SG,eo_EU,es_ES,fr_CA,fr_CH,fr_BE,fr_FR,it_CH,it_IT,ja_JP,ko_KR,nb_NO,nl_BE,nl_NL,pl_PL,pt_PT,ru_RU,sv_SE,tr_TR,zh_CN,zh_HK,zh_TW,am_ET,hi_IN,en_US,af_ZA,am_ET,ar_EG,ar_XB,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,en_XC,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,normal --preferred-density xxhdpi --version-code 27 --version-name 8.1.0   -R \\@/home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-overlay-list \\@/home/androidSource/out/target/product/whyred/obj/APPS/XiaomiDoze_intermediates/aapt2-flat-list )"
device/xiaomi/whyred/doze/res/values/styles.xml:34: error: resource layout/preference_category_material_settings (aka org.mokee.settings.doze:layout/preference_category_material_settings) not found.
device/xiaomi/whyred/doze/res/values/styles.xml:45: error: resource layout/preference_material_settings (aka org.mokee.settings.doze:layout/preference_material_settings) not found.
error: failed linking references.
[  0% 59/28724] Building Kernel Config
make: Entering directory '/home/androidSource/kernel/xiaomi/whyred'
make[1]: Entering directory '/home/androidSource/out/target/product/whyred/obj/KERNEL_OBJ'
  GEN     ./Makefile
#
# configuration written to .config
#
make[1]: Leaving directory '/home/androidSource/out/target/product/whyred/obj/KERNEL_OBJ'
make: Leaving directory '/home/androidSource/kernel/xiaomi/whyred'
make: Entering directory '/home/androidSource/kernel/xiaomi/whyred'
make[1]: Entering directory '/home/androidSource/out/target/product/whyred/obj/KERNEL_OBJ'
  GEN     ./Makefile
scripts/kconfig/conf  --savedefconfig=defconfig Kconfig
make[1]: Leaving directory '/home/androidSource/out/target/product/whyred/obj/KERNEL_OBJ'
make: Leaving directory '/home/androidSource/kernel/xiaomi/whyred'
[  0% 60/28724] target  C++: recovery <= bootable/recovery/recovery.cpp
ninja: build stopped: subcommand failed.

**Comment by xingrz** [comment]
你可能需要先了解下如何正确地在GitHub贴代码。

**Comment by TingyiChen** [comment]
缺了packagesettings

**Comment by buatge** [comment]
> 你可能需要先了解下如何正确地在GitHub贴代码。
我补一下报错信息
![image](https://user-images.githubusercontent.com/8622656/51161219-909b4280-18cc-11e9-893c-2a556fa55542.png)
