### ISSUE TITLE
Night Light - Issue

### ISSUE THREAD

**Issue by adi8900** [GuaiYiHu/android_device_xiaomi_whyred#6]
Hello. I picked adsp,audio, perf blobs and after building night light is dead,screen no begining yellow as should. People which picked this blobs on another roms have same issues...
Thanks for answer

**Comment by rashedsahaji** [comment]
Same Here I checked logs Pref blobs causing this I guess....

**Comment by GuaiYiHu** [comment]
Simply upgrading my code and lineageos code makes you know nothing about programming.
