### ISSUE TITLE
Sepolicy

### ISSUE THREAD

**Issue by GuaiYiHu** [GuaiYiHu/android_device_xiaomi_whyred#8]
/bin/bash -c "(rm -f /Volumes/Android/mkp/out/target/product/whyred/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows ) && (ASAN_OPTIONS=detect_leaks=0 /Volumes/Android/mkp/out/host/darwin-x86/bin/checkpolicy -M -c 		30 -o /Volumes/Android/mkp/out/target/product/whyred/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows /Volumes/Android/mkp/out/target/product/whyred/obj/ETC/sepolicy_neverallows_intermediates/policy.conf )"
libsepol.report_failure: neverallow on line 853 of system/sepolicy/private/system_server.te (or line 37004 of policy.conf) violated by allow system_server dalvikcache_data_file:file { execute };
libsepol.report_failure: neverallow on line 118 of system/sepolicy/private/domain.te (or line 27908 of policy.conf) violated by allow untrusted_app_25 sysfs:file { read open };
libsepol.report_failure: neverallow on line 118 of system/sepolicy/private/domain.te (or line 27908 of policy.conf) violated by allow system_server sysfs:file { read open };
libsepol.report_failure: neverallow on line 118 of system/sepolicy/private/domain.te (or line 27892 of policy.conf) violated by allow init proc:file { read setattr };
libsepol.report_failure: neverallow on line 118 of system/sepolicy/private/domain.te (or line 27892 of policy.conf) violated by allow system_server proc:file { ioctl read lock open };
libsepol.report_failure: neverallow on line 69 of system/sepolicy/private/app_neverallows.te (or line 25797 of policy.conf) violated by allow untrusted_app_25 sysfs:file { read open };
libsepol.report_failure: neverallow on line 512 of system/sepolicy/public/init.te (or line 17851 of policy.conf) violated by allow init sysfs:file { read write open };
libsepol.report_failure: neverallow on line 502 of system/sepolicy/public/init.te (or line 17841 of policy.conf) violated by allow init vendor_file:file { execute_no_trans };
libsepol.report_failure: neverallow on line 1396 of system/sepolicy/public/domain.te (or line 12169 of policy.conf) violated by allow qti_init_shell sysfs_lowmemorykiller:dir { write };
libsepol.report_failure: neverallow on line 1385 of system/sepolicy/public/domain.te (or line 12158 of policy.conf) violated by allow hal_perf_default hal_perf_default:capability { dac_read_search };
libsepol.report_failure: neverallow on line 1385 of system/sepolicy/public/domain.te (or line 12158 of policy.conf) violated by allow vendor_per_mgr vendor_per_mgr:capability { dac_read_search };
libsepol.report_failure: neverallow on line 1384 of system/sepolicy/public/domain.te (or line 12157 of policy.conf) violated by allow hal_perf_default hal_perf_default:capability { dac_override };
libsepol.report_failure: neverallow on line 1384 of system/sepolicy/public/domain.te (or line 12157 of policy.conf) violated by allow sensors sensors:capability { dac_override };
libsepol.report_failure: neverallow on line 1384 of system/sepolicy/public/domain.te (or line 12157 of policy.conf) violated by allow vendor_per_mgr vendor_per_mgr:capability { dac_override };
libsepol.report_failure: neverallow on line 1384 of system/sepolicy/public/domain.te (or line 12157 of policy.conf) violated by allow qti_init_shell qti_init_shell:capability { dac_override };
libsepol.report_failure: neverallow on line 1359 of system/sepolicy/public/domain.te (or line 12130 of policy.conf) violated by allow dpmd vendor_file:file { execute open };
libsepol.report_failure: neverallow on line 1359 of system/sepolicy/public/domain.te (or line 12130 of policy.conf) violated by allow system_server vendor_file:file { execute open };
libsepol.report_failure: neverallow on line 1315 of system/sepolicy/public/domain.te (or line 12076 of policy.conf) violated by allow hal_power_default debugfs:file { read open };
libsepol.report_failure: neverallow on line 1054 of system/sepolicy/public/domain.te (or line 11818 of policy.conf) violated by allow system_server dalvikcache_data_file:file { write };
libsepol.report_failure: neverallow on line 1042 of system/sepolicy/public/domain.te (or line 11804 of policy.conf) violated by allow radio vendor_file:file { execute_no_trans };
libsepol.report_failure: neverallow on line 1042 of system/sepolicy/public/domain.te (or line 11804 of policy.conf) violated by allow init vendor_file:file { execute_no_trans };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow system_server vendor_framework_file:file { execute };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow radio vendor_file:file { execute };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow dpmd vendor_file:file { execute };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow bluetooth vendor_file:file { execute };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow system_app vendor_file:file { execute };
libsepol.report_failure: neverallow on line 1031 of system/sepolicy/public/domain.te (or line 11783 of policy.conf) violated by allow system_server vendor_file:file { execute };
libsepol.report_failure: neverallow on line 906 of system/sepolicy/public/domain.te (or line 11544 of policy.conf) violated by allow vendor_init system_data_file:dir { write create setattr add_name };
libsepol.report_failure: neverallow on line 906 of system/sepolicy/public/domain.te (or line 11544 of policy.conf) violated by allow tee system_data_file:dir { read open };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init wpa_socket:dir { setattr };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init camera_data_file:dir { create setattr };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init nfc_data_file:dir { setattr search };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init wifi_data_file:dir { setattr search };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init dhcp_data_file:dir { setattr };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init tombstone_data_file:dir { write create setattr add_name search };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11516 of policy.conf) violated by allow vendor_init media_rw_data_file:dir { setattr };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11496 of policy.conf) violated by allow hal_drm_default media_data_file:dir { search };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11496 of policy.conf) violated by allow hal_camera_default camera_data_file:dir { write lock add_name remove_name search open };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11496 of policy.conf) violated by allow hal_fingerprint_default fingerprintd_data_file:dir { write add_name remove_name search };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11496 of policy.conf) violated by allow tee fingerprintd_data_file:dir { read write add_name search open };
libsepol.report_failure: neverallow on line 895 of system/sepolicy/public/domain.te (or line 11496 of policy.conf) violated by allow wcnss_service wifi_data_file:dir { search };
libsepol.report_failure: neverallow on line 867 of system/sepolicy/public/domain.te (or line 11444 of policy.conf) violated by allow init_fingerprint system_data_file:file { lock map open };
libsepol.report_failure: neverallow on line 867 of system/sepolicy/public/domain.te (or line 11444 of policy.conf) violated by allow hal_fingerprint_default fingerprintd_data_file:file { unlink rename };
libsepol.report_failure: neverallow on line 867 of system/sepolicy/public/domain.te (or line 11444 of policy.conf) violated by allow tee fingerprintd_data_file:file { create open };
libsepol.report_failure: neverallow on line 867 of system/sepolicy/public/domain.te (or line 11444 of policy.conf) violated by allow hal_camera_default camera_data_file:file { create setattr lock map unlink rename open };
libsepol.report_failure: neverallow on line 688 of system/sepolicy/public/domain.te (or line 11062 of policy.conf) violated by allow init vndbinder_device:chr_file { ioctl read write open };
libsepol.report_failure: neverallow on line 532 of system/sepolicy/public/domain.te (or line 10860 of policy.conf) violated by allow netmgrd default_prop:property_service { set };
libsepol.report_failure: neverallow on line 532 of system/sepolicy/public/domain.te (or line 10860 of policy.conf) violated by allow atfwd default_prop:property_service { set };
libsepol.report_failure: neverallow on line 532 of system/sepolicy/public/domain.te (or line 10860 of policy.conf) violated by allow hal_camera_default default_prop:property_service { set };
libsepol.report_failure: neverallow on line 532 of system/sepolicy/public/domain.te (or line 10860 of policy.conf) violated by allow qti_init_shell default_prop:property_service { set };
libsepol.report_failure: neverallow on line 519 of system/sepolicy/public/domain.te (or line 10847 of policy.conf) violated by allow system_server default_android_hwservice:hwservice_manager { find };
libsepol.report_failure: neverallow on line 519 of system/sepolicy/public/domain.te (or line 10847 of policy.conf) violated by allow cnd default_android_hwservice:hwservice_manager { add };
libsepol.report_failure: neverallow on line 517 of system/sepolicy/public/domain.te (or line 10845 of policy.conf) violated by allow system_server default_android_service:service_manager { add };
libsepol.report_failure: neverallow on line 510 of system/sepolicy/public/domain.te (or line 10838 of policy.conf) violated by allow vendor_init firmware_file:dir { create };
libsepol.report_failure: neverallow on line 510 of system/sepolicy/public/domain.te (or line 10838 of policy.conf) violated by allow vendor_init bt_firmware_file:dir { create };
libsepol.report_failure: neverallow on line 491 of system/sepolicy/public/domain.te (or line 10819 of policy.conf) violated by allow vendor_init firmware_file:dir { create };
libsepol.report_failure: neverallow on line 491 of system/sepolicy/public/domain.te (or line 10819 of policy.conf) violated by allow vendor_init adsprpcd_file:dir { create };
libsepol.report_failure: neverallow on line 491 of system/sepolicy/public/domain.te (or line 10819 of policy.conf) violated by allow vendor_init bt_firmware_file:dir { create };
libsepol.report_failure: neverallow on line 445 of system/sepolicy/public/domain.te (or line 10773 of policy.conf) violated by allow system_server dalvikcache_data_file:file { execute };
libsepol.report_failure: neverallow on line 404 of system/sepolicy/public/domain.te (or line 10732 of policy.conf) violated by allow system_server init:binder { call transfer };
libsepol.report_failure: neverallow on line 512 of system/sepolicy/public/app.te (or line 8871 of policy.conf) violated by allow shell kernel:system { syslog_read };

**Comment by srfarias** [comment]
I already fix a lot of denials 

https://github.com/srfarias/device_xiaomi_whyred/commit/5f40e49ddc52d3469097ccfa584f3d93eac1eb06

https://github.com/srfarias/device_xiaomi_whyred/commit/84dae2fce95589488444ad59427767175bd60e38

**Comment by GuaiYiHu** [comment]
> I already fix a lot of denials .. don't know if it's useful for u
> 
> [srfarias/device_xiaomi_whyred@5f40e49](https://github.com/srfarias/device_xiaomi_whyred/commit/5f40e49ddc52d3469097ccfa584f3d93eac1eb06)
> 
> [srfarias/device_xiaomi_whyred@84dae2f](https://github.com/srfarias/device_xiaomi_whyred/commit/84dae2fce95589488444ad59427767175bd60e38)
> 
> still fixing..

DONOT use audit2allow.

**Comment by srfarias** [comment]
Why?

**Comment by GuaiYiHu** [comment]
Done.

**Comment by rama982** [comment]
Time to kang

**Comment by GuaiYiHu** [comment]
Do not take it for granted that you all can use or kang my code all the time ever.

**Comment by twistloop** [comment]
This ^
